# The motd is seen in the server list. Please edit this.
Motd: '                   #d6a12e&lp#dba834&ll#e0b03a&la#e5b740&ly#ebbf46&l.#f0c64c&lI#f5cd52&ln#fad558&lg#ffdc5e&le#ffdc5e&ln#fad558&li#f5cd52&la#f0c64c&lM#ebbf46&lC#e5b740&l.#e0b03a&ln#dba834&le#d6a12e&lt                              #a34841Project is in developement'

# Discord settings
Discord:
  Bot:
    Token: 'token here'
    Guild-ID: 809319930754498580
    Linked-Role-ID: 1107022838109573160
  Webhook:
    # Webhook URL for the chat messages
    Chat: 'webhook here'

# The database URL can be found on the panel. It's called JDBC Connection String.
Database:
  Url: 'jdbc:mysql://please_update_this/'
  Address: 0.0.0.0
  Port: 25565
  Name: database-name
  User: database-user
  Password: database-password

# The list that is shown when a player clicks on tab.
# This is animated!
Tablist:
  Header:
    - "#ffea00&lI#ffe600&ln#ffe100&lg#ffdd00&le#ffd900&ln#ffd500&li#ffd000&la\n&7Welcome %player%\n"
    - "#ffe600&lI#ffea00&ln#ffe600&lg#ffe100&le#ffdd00&ln#ffd900&li#ffd500&la\n&7Welcome %player%\n"
    - "#ffe100&lI#ffe600&ln#ffea00&lg#ffe600&le#ffe100&ln#ffdd00&li#ffd900&la\n&7Welcome %player%\n"
    - "#ffdd00&lI#ffe100&ln#ffe600&lg#ffea00&le#ffe600&ln#ffe100&li#ffdd00&la\n&7Welcome %player%\n"
    - "#ffd900&lI#ffdd00&ln#ffe100&lg#ffe600&le#ffea00&ln#ffe600&li#ffe100&la\n&7Welcome %player%\n"
    - "#ffd500&lI#ffd900&ln#ffdd00&lg#ffe100&le#ffe600&ln#ffea00&li#ffe600&la\n&7Welcome %player%\n"
    - "#ffd000&lI#ffd500&ln#ffd900&lg#ffdd00&le#ffe100&ln#ffe600&li#ffea00&la\n&7Welcome %player%\n"
  Footer:
    - "\n&7play.IngeniaMC.net"


# These commands are allowed for players to execute and are put in the
# auto tab completion when a players presses tab in chat.
Player-Commands:
  - cosmetics
  - wands
  - wand
  - help
  - leave
  - msg
  - r
  - tell
  - react
  - plugins
  - pl
  - tps
  - link
  - unlink


# Levels
# And the amount of EXP needed to achieve them.
Levels:
  '1':
    Requirement: 25
    Rewards:
      - 'GS: 50'
  '2':
    Requirement: 50
    Rewards:
      - 'GS: 50'
  '3':
    Requirement: 100
    Rewards:
      - 'GS: 50'
  '4':
    Requirement: 150
    Rewards:
      - 'GS: 100'
  '5':
    Requirement: 200
    Rewards:
      - 'GS: 100'
      - 'WAND: happiness'
  '6':
    Requirement: 300
    Rewards:
      - 'GS: 100'
  '7':
    Requirement: 400
    Rewards:
      - 'GS: 100'
  '8':
    Requirement: 500
    Rewards:
      - 'GS: 200'
  '9':
    Requirement: 700
    Rewards:
      - 'GS: 200'
  '10':
    Requirement: 900
    Rewards:
      - 'GS: 300'
      - 'WAND: blocklauncher'
  '11':
    Requirement: 1200
    Rewards:
      - 'GS: 300'
  '12':
    Requirement: 1500
    Rewards:
      - 'GS: 400'
  '13':
    Requirement: 1900
    Rewards:
      - 'GS: 400'
  '14':
    Requirement: 2400
    Rewards:
      - 'GS: 500'
  '15':
    Requirement: 2900
    Rewards:
      - 'GS: 500'
  '16':
    Requirement: 3500
    Rewards:
      - 'GS: 600'
  '17':
    Requirement: 4200
    Rewards:
      - 'GS: 600'
  '18':
    Requirement: 4900
    Rewards:
      - 'GS: 600'
  '19':
    Requirement: 5700
    Rewards:
      - 'GS: 700'
  '20':
    Requirement: 6500
    Rewards:
      - 'GS: 700'
      - 'WAND: music'
  '21':
    Requirement: 7500
    Rewards:
      - 'GS: 700'
  '22':
    Requirement: 8700
    Rewards:
      - 'GS: 800'
  '23':
    Requirement: 9900
    Rewards:
      - 'GS: 800'
  '24':
    Requirement: 11000
    Rewards:
      - 'GS: 900'
  '25':
    Requirement: 12500
    Rewards:
      - 'GS: 1000'
  '26':
    Requirement: 14000
    Rewards:
      - 'GS: 1100'
  '27':
    Requirement: 15500
    Rewards:
      - 'GS: 1300'
  '28':
    Requirement: 17500
    Rewards:
      - 'GS: 1500'
  '29':
    Requirement: 19500
    Rewards:
      - 'GS: 1750'
  '30':
    Requirement: 21500
    Rewards:
      - 'GS: 2000'
      - 'WAND: speed'
  '31':
    Requirement: 24000
    Rewards:
      - 'GS: 2250'
  '32':
    Requirement: 26500
    Rewards:
      - 'GS: 2500'
  '33':
    Requirement: 29000
    Rewards:
      - 'GS: 3000'
  '34':
    Requirement: 32000
    Rewards:
      - 'GS: 3500'
  '35':
    Requirement: 35000
    Rewards:
      - 'GS: 4000'
  '36':
    Requirement: 38000
    Rewards:
      - 'GS: 5000'
  '37':
    Requirement: 42000
    Rewards:
      - 'GS: 6000'
  '38':
    Requirement: 46000
    Rewards:
      - 'GS: 7000'
  '39':
    Requirement: 50000
    Rewards:
      - 'GS: 8000'
  '40':
    Requirement: 54000
    Rewards:
      - 'GS: 9000'
      - 'WAND: antigravity'
  '41':
    Requirement: 58000
    Rewards:
      - 'GS: 10000'
  '42':
    Requirement: 62000
    Rewards:
      - 'GS: 12000'
  '43':
    Requirement: 66000
    Rewards:
      - 'GS: 14000'
  '44':
    Requirement: 70000
    Rewards:
      - 'GS: 16000'
  '45':
    Requirement: 75000
    Rewards:
      - 'GS: 18000'
  '46':
    Requirement: 80000
    Rewards:
      - 'GS: 20000'
  '47':
    Requirement: 85000
    Rewards:
      - 'GS: 22500'
  '48':
    Requirement: 90000
    Rewards:
      - 'GS: 25000'
  '49':
    Requirement: 95000
    Rewards:
      - 'GS: 27500'
  '50':
    Requirement: 100000
    Rewards:
      - 'GS: 35000'
      - 'WAND: cloak'
Guess-The-Word:
  - themepark
  - ingenia
  - ingeniamc
  - sandy town
  - magic village
  - castle
  - mainstreet
  - zipline
  - magic
  - special effects
  - passenger
  - roller coaster
  - cart
  - pants
  - shirt
  - hat
  - shoes
  - holy tomato
  - parktrain
  - mountainbike
  - vina tropica
  - snowball
  - snowball fight
  - ice
  - snowman
  - decoration
  - golden stars
  - discord
  - visitor
  - vip
  - vip plus
  - lead
  - team
  - achievement
  - firework
  - splash
  - attraction
  - frisbee
  - darkride
  - adventure
  - ferris wheel
  - playground
  - entertainment
  - station
  - jungle
  - savannah
  - forest
  - sakura
  - sakura valley